services:
  - type: web
    name: CS5942_Alpha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CS5942_Alpha.wsgi:application --bind 0.0.0.0:$PORT
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AlphaPostgreSQL
          property: connectionString
