services:
  - type: web
    name: CS5942_Alpha
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate --noinput
    startCommand: gunicorn final_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AlphaPostgreSQL
          property: connectionString