# Generated by Django 5.2.3 on 2025-07-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_backup'),
    ]

    operations = [migrations.AddField(
            model_name='chatmessage',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
