# Generated by Django 5.2.3 on 2025-07-30 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_backup'),
        ('task', '0016_alter_taskapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read', 'is_group'], name='communicati_receive_735293_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['task', 'is_read', 'is_group'], name='communicati_task_id_2725e3_idx'),
        ),
    ]
