# Generated by Django 5.2.3 on 2025-07-24 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_chatmessage_is_read_alter_chatmessage_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='onetoonechatsession',
            constraint=models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='user1_less_than_user2'),
        ),
    ]
