# Generated by Django 5.2.3 on 2025-06-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('unselected', 'unselected'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
