# Generated by Django 5.2.3 on 2025-07-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskapplication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='patient',
            new_name='client',
        ),
    ]
