# Generated by Django 5.2.3 on 2025-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_patient_task_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open for application'), ('selected', 'Selecting Done'), ('onoging', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
