# Generated by Django 5.2.3 on 2025-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
