# Generated by Django 5.2.3 on 2025-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_taskapplication_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open for application'), ('selected', 'Selecting Done'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
