# Generated by Django 5.2.3 on 2025-07-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_status'),
        ('user', '0008_clientprofile_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('work_area', models.ManyToManyField(to='user.supporttype')),
            ],
        ),
    ]
