# Generated by Django 5.2.3 on 2025-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
