# Generated by Django 5.2.3 on 2025-07-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_room_name'),
        ('task', '0010_feedback_starrelation'),
    ]

    operations = [
    ]
