# Generated by Django 5.2.3 on 2025-07-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_merge_0008_task_room_name_0010_feedback_starrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='room_name',
        ),
    ]
