# Generated by Django 5.2.3 on 2025-07-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_remove_task_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='is_auto_matched',
            field=models.BooleanField(default=False),
        ),
    ]
