# Generated by Django 5.2.3 on 2025-07-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_taskapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
