# Generated by Django 5.2.3 on 2025-07-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_taskapplication_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('unselected', 'unselected'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
