# Generated by Django 5.2.3 on 2025-08-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_taskapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='task.task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrecord',
            unique_together={('task', 'volunteer')},
        ),
    ]
