"""
Django settings for final_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# 强制加载 .env 文件
load_dotenv()  # 确保在所有情况下加载
if not os.getenv('DATABASE_URL'):
    raise ValueError("DATABASE_URL environment variable not set. Please check .env file.")
print("DEBUG: Loaded DATABASE_URL =", os.environ.get('DATABASE_URL'))  # 调试

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'shallion-support-files'
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_OBJECT_PARAMETERS = {}

MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-i!o^^a8m_sz=(_5e_c07nyutwzr(fdu+uihy5=gpr^lwvwpotb'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'mangoairport-artistbanana-8000.codio-box.uk', 'cs5942-alpha.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://cs5942-alpha.onrender.com',
    'https://mangoairport-artistbanana-8000.codio-box.uk',
    'http://localhost:8000',
    'http://127.0.0.1:8000',  # 确保包含本地开发环境
    'http://127.0.0.1',  # 覆盖所有本地请求
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # 确保静态文件应用已启用
    'user',
    'volunteer',
    'matching',
    'payment',
    'communication',
    'adminpanel',
    'channels',
    'task',
    'storages',
]

ASGI_APPLICATION = 'final_project.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
        'expire': 120,
        'timeout': 30,
        'retry_attempts': 3,  # 添加重试
    },
}

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 全局模板目录
        'APP_DIRS': True,  # 启用应用内模板查找
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',  # 添加静态文件上下文处理器
            ],
        },
    },
]

WSGI_APPLICATION = 'final_project.wsgi.application'

IS_TESTING = 'test' in os.sys.argv
IS_DEVELOPMENT = os.environ.get('DJANGO_DEVELOPMENT') == '1'

if IS_TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',  # 使用内存数据库
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'),
            conn_max_age=600,
            ssl_require=os.environ.get('RENDER') == 'true'
        )
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/London'
USE_I18N = True
USE_TZ = True

# 确保 Session 配置
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 默认数据库存储
CSRF_COOKIE_SECURE = False  # 开发环境禁用安全 Cookie
SESSION_COOKIE_SECURE = False  # 开发环境禁用安全 Session Cookie

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # 确保静态文件目录正确配置
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'