# Generated by Django 5.2.3 on 2025-06-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('volunteer', 'Volunteer'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('consent_safeguard', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pip_certificate', models.FileField(blank=True, null=True, upload_to='certificates/pip/')),
                ('adp_certificate', models.FileField(blank=True, null=True, upload_to='certificates/adp/')),
                ('lwc_certificate', models.FileField(blank=True, null=True, upload_to='certificates/lwc/')),
                ('eligibility_confirmed', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('support_areas', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_times', models.JSONField(blank=True, default=dict)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('dietary_needs', models.TextField(blank=True, null=True)),
                ('has_pets', models.BooleanField(default=False)),
                ('pets_type', models.CharField(blank=True, max_length=100, null=True)),
                ('certifications', models.ManyToManyField(to='user.certificationtype')),
                ('conditions', models.ManyToManyField(blank=True, to='user.conditiontype')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_to_focus', models.CharField(blank=True, max_length=255, null=True)),
                ('project_goal', models.TextField(blank=True, null=True)),
                ('expected_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('consent_data_use', models.BooleanField(default=False)),
                ('agreement_ethics', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('is_for_credit', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('pvg_level', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
