# Generated by Django 5.2.3 on 2025-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='course',
            new_name='university_couse',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='university',
        ),
    ]
