# Generated by Django 5.2.3 on 2025-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_course_volunteerprofile_university_couse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='university_couse',
            new_name='university_course',
        ),
    ]
