# Generated by Django 5.2.3 on 2025-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_university_couse_volunteerprofile_university_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='support_areas',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='support_areas',
            field=models.ManyToManyField(blank=True, to='user.supporttype'),
        ),
    ]
