# Generated by Django 5.2.3 on 2025-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_supporttype_remove_clientprofile_support_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='pvg_file',
            field=models.FileField(blank=True, null=True, upload_to='pvg/'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='pvg_level',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('processing', 'Processing'), ('pending', 'Pending'), ('do_not_have', 'I do not have a PVG yet')], max_length=50, null=True),
        ),
    ]
