# Generated by Django 5.2.3 on 2025-06-21 15:47

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_volunteerprofile_pvg_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='other_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='other_support',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='preferred_tasks',
            field=models.ManyToManyField(blank=True, to='user.supporttype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
