# Generated by Django 5.2.3 on 2025-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='diagnosis',
            field=models.FileField(blank=True, null=True, upload_to='certificates/diagnosis/'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='nhs_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/nhs/'),
        ),
    ]
