# Generated by Django 5.2.3 on 2025-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_clientprofile_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='accept_pets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='available_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='available_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='preferred_distance_km',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
