# Generated by Django 5.2.3 on 2025-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_volunteerprofile_accept_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
