# Generated by Django 5.2.3 on 2025-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='eligibility_confirmed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
