# Generated by Django 5.2.3 on 2025-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_clientprofile_eligibility_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='assigned_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='max_task_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
