# Generated by Django 5.2.3 on 2025-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_volunteerprofile_assigned_tasks_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='other_support',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='preferred_times',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='support_areas',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='availability',
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='pvg_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/pvg/'),
        ),
    ]
