# Generated by Django 5.2.3 on 2025-07-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_pvgleveltype_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvgleveltype',
            name='code',
            field=models.CharField(default='default_code', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pvgleveltype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
